stages:
  - test
  - deploy

step-develop:
  stage: test
  before_script:
    - echo here we should have the before script
  only:
    - development
  tags:
    - development
  script:
    - echo here we should at least be running tests

step-deploy-production:
  stage: test
  before_script:
    - export ELASTIC_ADDRESS=$ELASTIC_ADDRESS_KEY
    - export ELASTIC_PORT=$ELASTIC_PORT_KEY
    - export PORT=$PORT_KEY
    - export API_ADDRESS_PROD=$API_ADDRESS_PROD_KEY
    - export API_PORT_PROD=$API_PORT_PROD_KEY

  only:
    - master
  tags:
    - master
  script:
    - 'VERSION=$(curl -Ss --request GET --header "PRIVATE-TOKEN: DJxgGGJxoE94ZWqYDL4w" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/repository/tags" | jq -r ".[0] | .name")'
    - test -z "$VERSION" && echo "no version tag found" && exit 1
    - echo 'Version '$VERSION ' was found'
    - export DOCKER_GIT_CREDENTIALS="$(cat ~/.git-credentials)"
    - docker build --build-arg DOCKER_GIT_CREDENTIALS --build-arg ELASTIC_ADDRESS_ENV=$ELASTIC_ADDRESS_KEY -t registry.gitlab.com/jebo87/makako-gateway:$VERSION  .
    - docker push registry.gitlab.com/jebo87/makako-gateway:$VERSION
    - docker tag registry.gitlab.com/jebo87/makako-gateway:$VERSION registry.gitlab.com/jebo87/makako-gateway:latest
    - docker push registry.gitlab.com/jebo87/makako-gateway:latest
    - docker image prune -f
    - kubectl apply -f /mnt/linux/k8s/MakakoLabs/makako-gateway.yaml
