before_script:
  - docker info

build_image:
  script:
    - docker build --build-arg -t registry.gitlab.com/jebo87/makako-gateway:0.1 .
    - docker push registry.gitlab.com/jebo87/makako-gateway:0.1
